extends SelectionPropertyField
class_name CheckTogglePropertyField
## The [SelectionPropertyField] generated by [CheckToggleProperty].
##
## Allows the user to interact with the properties of [DraggableObject]s through the [SelectionMenu].
## [br]Executes the definition given by a [CheckToggleProperty].[br]
## [br]The function [member SelectionProperty.commandName] of the [member SelectionPropertyField.associatedObject] will be called when:
## [br] - the [member checkbox] emits [signal CheckBox.toggled].

#region Member Variables
## The [CheckBox] for the [CheckToggleProperty]
var checkbox : CheckBox
#endregion

#region Initialization
## Class Initialization
func _init(obj : DraggableObject, property : CheckToggleProperty):
	super(obj, property) #calls SelectionPropertyField._init()
	
	# create and setup the checkbox
	checkbox = CheckBox.new()
	checkbox.set_pressed_no_signal(property.defaultValue) #set whether it's checked to the default value provided
	self.add_child(checkbox)
	
	#connect command
	checkbox.toggled.connect(Callable(obj,property.commandName))
	#the toggled signal sends the bool value of the checkbox
#endregion
