extends SelectionPropertyField
class_name HeaderPropertyField
## The [SelectionPropertyField] generated by [HeaderProperty].
##
## Allows the user to interact with the properties of [DraggableObject]s through the [SelectionMenu].
## [br]Executes the definition given by a [HeaderProperty].
## [br][br]Displays a non-interactable header/title to help describe a group of other [SelectionPropertyField]s
## [br][br]The function [member SelectionProperty.commandName] of the [member SelectionPropertyField.associatedObject] has no effect.

#region Constants
## The style applied to headers. Provided mainly to give a consisten (but also enlarged) font.
const headerStyleLocation = "res://UI/header_style.tres"
#endregion

#region Initialization
## Class Initialization
func _init(obj : DraggableObject, property : HeaderProperty):
	super(obj, property) #calls SelectionPropertyField._init()
	
	# Change text to header value
	var headerObj = self.getNameObject()
	headerObj.text = property.header
	# Change theme to the header theme
	var headerStyle = load(headerStyleLocation)
	headerObj.theme = headerStyle
	#Make it take up as much space as it can
	headerObj.size_flags_horizontal = Control.SIZE_EXPAND_FILL
#endregion

#region Functions

#endregion
