extends SelectionPropertyField
class_name SeperatorPropertyField
## The [SelectionPropertyField] generated by [SeperatorProperty].
##
## Allows the user to interact with the properties of [DraggableObject]s through the [SelectionMenu].
## [br]Executes the definition given by a [SeperatorProperty].
## [br][br]Displays a [HSeparator] in the [SelectionMenu] to visually group together and/or seperate some [SeperatorPropertyField]s.
## [br][br]The function [member SelectionProperty.commandName] of the [member SelectionPropertyField.associatedObject] will be called when:
## [br] - [member %object%] emits [signal %object%.%signal%]

#region Member Variables
## The [HSeparator]
var line
#endregion

#region Initialization
## Class Initialization
func _init(obj : DraggableObject, property : SeperatorProperty):
	super(obj, property) #calls SelectionPropertyField._init()
	
	# generate and add the line
	line = HSeparator.new()
	add_child(line)
	self.propertyName.queue_free()
	line.size_flags_horizontal = SIZE_EXPAND_FILL #makes the line fill up the full available width
#endregion

#region Functions

#endregion
